name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 4'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, '8.0', 8.1, 8.2]
        laravel: ['6.0', '7.0', '8.0', '9.0', '10.0']
        exclude:
          - php: 8.1
            laravel: '6.0'
          - php: 8.2
            laravel: '6.0'
          - php: 8.1
            laravel: '7.0'
          - php: 8.2
            laravel: '7.0'
          - php: 8.2
            laravel: '8.0'
          - php: 7.3
            laravel: '9.0'
          - php: 7.4
            laravel: '9.0'
          - php: 7.3
            laravel: '10.0'
          - php: 7.4
            laravel: '10.0'
          - php: '8.0'
            laravel: '10.0'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-laravel${{ matrix.laravel }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-laravel${{ matrix.laravel }}

      - name: Install dependencies
        run: |
          composer require laravel/framework ^${{ matrix.laravel }} --dev --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit
